/** 
 * Auto-generated by effect-start.
 */

import type { Router } from "effect-start"

const layout__ = {
  path: "/",
  load: () => import("./_layout.tsx"),
} as const

const page__ = {
  path: "/",
  parent: layout__,
  load: () => import("./_page.tsx"),
} as const

const server__funding_json = {
  path: "/funding.json",
  load: () => import("./funding.json/_server.ts"),
} as const

const server__live_json = {
  path: "/live.json",
  load: () => import("./live.json/_server.ts"),
} as const

const server__map_json = {
  path: "/map.json",
  load: () => import("./map.json/_server.ts"),
} as const

const server__live__preview_json = {
  path: "/live/preview.json",
  load: () => import("./live/preview.json/_server.ts"),
} as const

const server__map__preview_json = {
  path: "/map/preview.json",
  load: () => import("./map/preview.json/_server.ts"),
} as const

export const Layouts: Router.LayoutRoutes = [
  layout__
] as const

export const Pages: Router.PageRoutes = [
  page__
] as const

export const Servers: Router.ServerRoutes = [
  server__funding_json,
  server__live_json,
  server__map_json,
  server__live__preview_json,
  server__map__preview_json
] as const
 